site_name: PyRGFROSH
site_url: https://vasulab.github.io/PyRGFROSH
repo_name: VasuLab/PyRGFROSH
repo_url: https://github.com/VasuLab/PyRGFROSH
edit_uri: tree/main/docs/

nav:
  - Home:
      - index.md
      - License: license.md
  - User Guide: guide.md
  - API Reference: reference.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.tabs
    - toc.integrate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            members_order: source
            show_root_full_path: false
            show_root_heading: true
            show_root_toc_entry: true
            show_source: false
          selection:
            filters:
              - "!^_"  # exclude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

extra:
  generator: false

extra_css:
- css/style.css
