site_name: Python RGFROSH
site_url: https://vasulab.github.io/RGFROSH
repo_name: VasuLab/RGFROSH
repo_url: https://github.com/VasuLab/RGFROSH
edit_uri: tree/main/docs/

nav:
  - Home:
      - index.md
      - License: license.md
  - User Guide:
    - guide/index.md
    - Interfaces: guide/interfaces.md
  - API Reference:
    - rgfrosh.shock: reference/shock.md
    - rgfrosh.interface: reference/interface.md
    - rgfrosh.constants: reference/constants.md

theme:
  name: material
  font:
    code: Consolas
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.tabs
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            docstring_section_style: list
            members_order: source
            merge_init_into_class: true
            show_signature_annotations: true
            show_root_heading: true
            show_root_full_path: false
            show_source: false

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

watch:
  - rgfrosh

extra:
  generator: false

extra_css:
- css/style.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
