name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event_name == 'push' }}
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - run: |
          pip install .
          pip install numpy
          pip install typing-extensions
          pip install CoolProp
          pip install mkdocs-material
          pip install mkdocstrings-python
      - run: mkdocs gh-deploy --force
